### ISSUE TITLE
About speed

### ISSUE THREAD

**Issue by zhancr** [ojmakhura/hdbscan#1]
Is the speed of this C++ version is tested?  whether this is fast than the followed  python version ?https://github.com/scikit-learn-contrib/hdbscan

**Comment by ojmakhura** [comment]
I will admit, I haven't done serious comparison for speed. But the implementation itself is designed to be fast. That is why I ended up using C instead of C++. It uses OpenMP whenever possible especially when calculating the distances. Also for the distances, it only calculates the top half of the distance matrix since the bottom half is the same.

The other thing is that with this implementation you can test various values of minPts without recalculating the distance matrix which makes it super fast.

**Comment by trig-ger** [comment]
Does this library include the accelerated version (2017) of the HDBSCAN algo?
The paper: https://arxiv.org/abs/1705.07321
The implementation in Python: https://github.com/scikit-learn-contrib/hdbscan

**Comment by ojmakhura** [comment]
No. This library was created based on the original HDBSCAN paper by Campelo et al.
